### ISSUE TITLE
Убрать у всех элементов фиксированную высоту. Контент страницы может меняться, текста может стать больше, соответственно фиксированная высота может сломать верстку

### ISSUE THREAD

**Issue by igosheva** [GyGaByyyTe/gygabyyyte.github.io#1]
https://github.com/GyGaByyyTe/gygabyyyte.github.io/blob/1a78b57df1f1d860fbc023fe6df998c7368b56f1/css/styles.css#L82

**Comment by igosheva** [comment]
Тоже самое касается ширины этого элемента

**Comment by GyGaByyyTe** [comment]
убрал лишние указания ширины и высоты у блоков
