### ISSUE TITLE
Убрать фиксированную высоту и ширину

### ISSUE THREAD

**Issue by igosheva** [GyGaByyyTe/gygabyyyte.github.io#12]
https://github.com/GyGaByyyTe/gygabyyyte.github.io/blob/1a78b57df1f1d860fbc023fe6df998c7368b56f1/css/styles.css#L244

**Comment by igosheva** [comment]
И вообще это избыточная обертка.

**Comment by igosheva** [comment]
Внутри стрелки не относятся к основному списку пагинации)

**Comment by GyGaByyyTe** [comment]
pages__buttons  оставил, потому что она теперь оборачивает стрелки и лист
стрелки вынес отдельно от листа
