### ISSUE TITLE
Общее значение верхнего маржина этого элемента и header__right можно вынести в верхний паддинг header

### ISSUE THREAD

**Issue by igosheva** [GyGaByyyTe/gygabyyyte.github.io#15]
https://github.com/GyGaByyyTe/gygabyyyte.github.io/blob/b3721cf014f51b1af01738e3932022b6bd017bbe/css/blocks/header.css#L12

**Comment by GyGaByyyTe** [comment]
Общее расстояние вынесено в паддинг всему хедеру
