### ISSUE TITLE
Этот элемент не должен быть на всю ширину родителя. Сейчас слева пустое пространство тоже кликабельно

### ISSUE THREAD

**Issue by igosheva** [GyGaByyyTe/gygabyyyte.github.io#16]
https://github.com/GyGaByyyTe/gygabyyyte.github.io/blob/b3721cf014f51b1af01738e3932022b6bd017bbe/css/blocks/contacts.css#L1

**Comment by GyGaByyyTe** [comment]
Исправлено.
