### ISSUE TITLE
Убрать фиксированную высоту и ширину. Чтобы этот блок был высотой с картинку, нужно задать картинке vertical-align: top;

### ISSUE THREAD

**Issue by igosheva** [GyGaByyyTe/gygabyyyte.github.io#3]
https://github.com/GyGaByyyTe/gygabyyyte.github.io/blob/1a78b57df1f1d860fbc023fe6df998c7368b56f1/css/styles.css#L96

**Comment by GyGaByyyTe** [comment]
убрал размеры, задал свойство vertical-align: top;
