### ISSUE TITLE
Можно убрать фиксированную ширину и задать просто маржин справа на ту ширину, на которую должен отталкиваться справа этот блок от main__content

### ISSUE THREAD

**Issue by igosheva** [GyGaByyyTe/gygabyyyte.github.io#36]
https://github.com/GyGaByyyTe/gygabyyyte.github.io/blob/09ebdde4299853189cc966c05492695b0169baa7/css/layout/base.css#L49

**Comment by GyGaByyyTe** [comment]
сделал, но пришлось задать максимальную ширину для элемента списка, иначе длинные слова в навигации все ломали
