### ISSUE TITLE
Это не заголовок, а просто текст. Так что нужно использовать тег абзаца p

### ISSUE THREAD

**Issue by igosheva** [GyGaByyyTe/gygabyyyte.github.io#38]
https://github.com/GyGaByyyTe/gygabyyyte.github.io/blob/09ebdde4299853189cc966c05492695b0169baa7/comments.html#L179

**Comment by GyGaByyyTe** [comment]
валидатор требует в каждой секции наличие h2-h6, пришлось добавить скрытый
