### ISSUE TITLE
В инлайновые стили нужно выносить только background-image, остальное переместить в css

### ISSUE THREAD

**Issue by igosheva** [GyGaByyyTe/gygabyyyte.github.io#49]
https://github.com/GyGaByyyTe/gygabyyyte.github.io/blob/48289f098207dd88df43eb9285d3980564353964/level2/app/index.html#L110

**Comment by igosheva** [comment]
reviews__img - тоже самое

**Comment by GyGaByyyTe** [comment]
Готоуа
