### ISSUE TITLE
Лучше скрыть элемент через visibility: hidden;. И составные имена классов пишутся через "-", тут я думаю обычного "hidden" будет достаточно)

### ISSUE THREAD

**Issue by igosheva** [GyGaByyyTe/gygabyyyte.github.io#9]
https://github.com/GyGaByyyTe/gygabyyyte.github.io/blob/1a78b57df1f1d860fbc023fe6df998c7368b56f1/css/styles.css#L191

**Comment by GyGaByyyTe** [comment]
Исправил имя класса и реализацию в файле css
